#!/bin/bash

JLINK="00:22:c7:07:17:a2"


__DB="$HOME/.getIPFromMac"
__SAVE=""
__VERBOSE=""
__MAC=""
__ID=""
__PING=""

usage ( )
{
	echo "$0 -m xx:xx:xx:xx:xx:xx [-s NAME] [-d path/file] [-v]"
	echo "    to get IP from provided MAC"
	echo "$0 NAME [-d path/file] [-v]"
	echo "    to get an IP through a MAC found in database file"
	echo ""
	echo "-d|--database   save file for saved mac"
	echo "-h|--help       this windows"
	echo "-m|--mac        mac searched"
	echo "-s|--save       save ID and mac in database file"
	echo "-v|--verbose    verbose mode"
	echo "-p|--ping       execute a broadcasted ping"
	echo "                 -p netAddr/mask"
}

for arg in $@
do
	case $arg in
		-h|--help)
			usage $0
			;;
		-v|--verbose)
			__VERBOSE="true"
			;;
		-m|--mac|-s|--save|-d|--database|-p|--ping)
			last=$arg;
			;;
		*)
			case $last in
				-m|--mac)
					__MAC=$arg
					;;
				-s|--save)
					__SAVE=$arg
					;;
				-d|--database)
					__DB=$arg
					;;
				-p|--ping)
					__PING=$arg
					;;
				*)
					__ID=$arg
			esac
			last=""
			;;
	esac
done

if [ "$__MAC" == "" ] && [ "$__DB" != "" ] && [ -f "$__DB" ]; then
	if [ "$__VERBOSE" == "true" ]; then
		echo "$__DB contain"
		echo "--------------------------------------------------"
		cat $__DB
		echo "--------------------------------------------------"
		printf "\nget IP from %s " $__ID
	fi

	__MAC=$( cat $__DB | grep -E "^$__ID=" | cut -d"=" -f2 )
fi

if [ "$__MAC" != "" ]; then
	__MAC=$(echo $__MAC | tr '[:upper:]' '[:lower:]')
	echo $__MAC

	if [ "$__PING" != "" ]; then
		# need to get netIP from interface
		nmap -sP $__PING
	fi

	if [ "$__VERBOSE" == "true" ]; then
		echo "get ip from $__MAC"
		printf "IP is: "
	fi

	__IP=$(arp -a | grep "$__MAC" | cut -d" " -f2 | cut -d"(" -f2 | cut -d")" -f1)

	if [ "$__VERBOSE" == "true" ]; then
		echo $__IP
	fi

	if [ "$__IP" == "" ]; then
		__MASKS=() # nb de bit du mask
		__IPS=() # ip du reseau
		while read line
		do
			mask=$(echo $line | cut -d" " -f4)
			count=0
			for m in $( echo $mask | cut -d"." -f1- --output-delimiter " " )
			do
				while [ "$m" != "0" ];
				do
					count=$(( $count + $(( $m % 2 )) ))
					m=$(( $m / 2 ))
				done
			done
			__MASKS+=($count)

			ip=$(echo $line | cut -d" " -f2)
			IFS=. read -r i1 i2 i3 i4 <<< $ip
			IFS=. read -r m1 m2 m3 m4 <<< $mask

			__IPS+=($(echo "$((i1 & m1)).$((i2 & m2)).$((i3 & m3)).$((i4 & m4))"))
		done <<< $(ifconfig | grep "inet " | sed -r 's/\s+/ /g' | sed -r 's/^\s//g' | grep -v " 127")

		echo "IP for the ping mode"
		for i in ${!__IPS[@]}
		do
			echo "${__IPS[$i]}/${__MASKS[$i]}"
		done
		exit 1
	fi


	if [ "$__SAVE" != "" ] && [ "$__DB" != "" ] && [ -f "$__DB" ]; then
		if [ "$__VERBOSE" == "true" ]; then
			echo "Save $__SAVE=$__MAC in $__DB"
		fi

		grep -vE "^$__SAVE=" $__DB > $__DB.tmp
		rm $__DB
		mv $__DB.tmp $__DB
		printf "$__SAVE=$__MAC\n" >> "$__DB"
	fi
fi
