#!/bin/bash

LAST=""
UPLOAD="KO"
UP_DIR=""
TEX=""
PDF=""
FLAG=""

for PARAM in $@
do
	case $PARAM in
		-f)
			LAST="file"
			;;
		-h|--help)
			echo display this window
			exit
			;;
		-gu)
			UPLOAD="OK"
			LAST="google_upload"
			;;
		*)
			case $LAST in
				google_upload)
					if [ "$UP_DIR" != "" ]; then
						echo $UP_DIR will be replaced by $PARAM
						echo $PARAM wil be the next google drive upload directory
					fi
					UP_DIR=$PARAM
					;;
				file)
					TEX="$TEX $PARAM"
					;;
				*)
					echo unknow param $PARAM
					;;
			esac
			;;
	esac
done

if [ "$TEX" == "" ]; then
	TEX=$(find . | grep -E "*.tex$")
fi

for DOC in $TEX
do
	echo $DOC
	BASE=$( echo $DOC | rev | cut -d '.' -f 2- | rev )
	PS=$BASE".ps"
	PDF=$BASE".pdf"
	DVI=$BASE".dvi"
	AUX=$BASE".aux"
	FLAG=$( [ "$(grep minted $DOC)" != "" ] && echo "-shell-escape" || echo "" )

	# first compilation
	latex $FLAG $DOC 1>/dev/null
	RET_1=$?
	
	# generate the bib element if needed
	if [ "$RET_1" == 0 ];
	then
		bibtex $AUX 1>/dev/null
		RET_2=$?
	fi
	
	# second compilation if no bib or first if bib exist
	if [ "$RET_1" == 0 ];
	then
		latex $FLAG $DOC 1>/dev/null
		RET=$?
	fi
	
	# second compilation if bib exist
	if [ "$RET" == 0 ] && [ "$RET_2" == 0 ];
	then
		latex $FLAG $DOC 1>/dev/null
		RET=$?
	fi

	# second compilation if bib exist
	if [ "$RET" == 0 ] && [ -f $DVI ];
	then
		dvips $DVI -o $PS
		ps2pdf $PS $PDF
		RET=$?
	fi

	[ "$RET" == 0 ] && echo -e "\e[1;32mall done perfectly\e[0m"

	[ "$RET" == 0 ] && [ "$UPLOAD" == "OK" ] && google_upload $PDF $UP_DIR
done

