#!/bin/bash

LAST=""
UPLOAD="KO"
UP_DIR=""
TEX=""
PDF=""
FLAG=""
ONCE=""

for PARAM in $@
do
	case $PARAM in
		-f)
			LAST="file"
			;;
		-h|--help)
			echo display this window
			exit
			;;
		-gu)
			UPLOAD="OK"
			LAST="google_upload"
			;;
		*)
			case $LAST in
				google_upload)
					if [ "$UP_DIR" != "" ]; then
						echo $UP_DIR will be replaced by $PARAM
						echo $PARAM wil be the next google drive upload directory
					fi
					UP_DIR=$PARAM
					;;
				file)
					TEX="$TEX $PARAM"
					;;
				*)
					echo unknow param $PARAM
					;;
			esac
			;;
	esac
done

if [ "$TEX" == "" ]; then
	TEX=$(find . | grep -E "*.tex$")
fi

for DOC in $TEX
do
	echo $DOC
	PDF=$( echo $DOC | rev | cut -d '.' -f 2- | rev ).pdf
	AUX=$( echo $DOC | rev | cut -d'.' -f 2- | rev ).aux
	FLAG=$( [ "$(grep minted $DOC)" != "" ] && echo "-shell-escape" || echo "" )

	# first compilation
	pdflatex $FLAG $DOC
	RET_1=$?
	
	# generate the bib element if needed
	if [ "$RET_1" == 0 ];
	then
		bibtex $AUX
		RET_2=$?
	fi
	
	# second compilation if no bib or first if bib exist
	if [ "$RET_1" == 0 ];
	then
		pdflatex $FLAG $DOC
		RET=$?
	fi
	
	# second compilation if bib exist
	if [ "$RET" == 0 ] && [ "$RET_2" != "" ] && [ "$RET_2" == 0 ];
	then
		pdflatex $FLAG $DOC
		RET=$?
	fi

	[ "$RET" == 0 ] && echo -e "\e[1;32mall done perfectly\e[0m"

	[ "$RET" == 0 ] && [ "$UPLOAD" == "OK" ] && google_upload $PDF $UP_DIR
done

